# Generated by Django 5.0.2 on 2025-04-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackrating",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
