# Generated by Django 5.0.2 on 2025-04-20 20:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("track", "Track"),
                            ("album", "Album"),
                            ("rating", "Rating"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("spotify_id", models.CharField(max_length=100)),
                ("spotify_name", models.CharField(max_length=255)),
                ("spotify_artist", models.CharField(max_length=255)),
                ("spotify_image_url", models.URLField(blank=True)),
                ("spotify_preview_url", models.URLField(blank=True, null=True)),
                ("spotify_url", models.URLField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
