# Generated by Django 5.0.2 on 2025-04-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_post_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
    ]
