# Generated by Django 5.0.2 on 2025-05-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
