# Generated by Django 5.0.2 on 2025-05-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_top_album1_id_user_top_album1_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="listen_later",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
